apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: ai-role
spec:
  rules:
  - services: ["ai.mesh-arena.svc.cluster.local"]
    methods: ["POST"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-ai-role
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "ai-role"
