apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: stadium-role
spec:
  rules:
  - services: ["stadium.mesh-arena.svc.cluster.local"]
    methods: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-stadium-role
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "stadium-role"
