apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: stadium-role
spec:
  rules:
  - services: ["stadium.mesh-arena.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-productpage-viewer
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "productpage-viewer"
